### ISSUE TITLE
Automatic repository creation

### ISSUE THREAD

**Issue by marcingrzejszczak** [microservice-hackathon/ansible-microservice-hackathon#11]
What needs to be automatized is:

  - Cloning of boot-microservice (`git clone https://github.com/4finance/boot-microservice.git`) for
     - FraudDetectionService
     - LoanApplicationService
     - LoanApplicationDecisionMaker
     - MarketingOfferGenerator
  - Cloning of boot-microservice-gui (`git clone https://github.com/4finance/boot-microservice.git -b boot-microservice-gui` )for
     - ReportingService
     - ClientService

For those repositories we need to alter
  - .travis.yml ?
  - application.yml
```
metrics.path.app=reporting-service
stubrunner.stubs.repository.root=http://nexus.hackathon.dev.4finance.net:8081/nexus/content/repositories/releases/
stubrunner.stubs.group=com.ofg
stubrunner.stubs.module=stub-definitions
graphite.host=graphite.hackathon.dev.4finance.net
server.port=8053
```

server.port - needs to be picked

**Comment by wybczu** [comment]
Done.
